version: "3"
services:
  php:
    build:
      context: ./configs
      dockerfile: php74.dockerfile
    env_file:
      - configs/vars.env
    volumes:
      - ./:/var/www
      - ./configs/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  nginx:
    image: library/nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./configs/nginx.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php
    links:
      - php